# Generated by Django 5.1.4 on 2024-12-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0002_addfaculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addfaculty',
            name='contactNo',
        ),
        migrations.AddField(
            model_name='addfaculty',
            name='contact',
            field=models.CharField(default='', max_length=100),
        ),
    ]
