# Generated by Django 5.1.4 on 2024-12-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0007_addleisurepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='facultyname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
