# Generated by Django 5.1.4 on 2024-12-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0008_schedule_facultyname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='facultyname',
        ),
        migrations.AddField(
            model_name='schedule',
            name='facultyname1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
