# Generated by Django 5.1.4 on 2024-12-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0009_remove_schedule_facultyname_schedule_facultyname1'),
    ]

    operations = [
        migrations.CreateModel(
            name='invigilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=100)),
            ],
        ),
    ]
