# Generated by Django 5.1.4 on 2024-12-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0010_invigilation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='invigilation',
        ),
    ]
