# Generated by Django 5.1.1 on 2025-01-05 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0012_alter_addleisurepage_facultyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addleisurepage',
            name='facultyname',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='duty.addfaculty'),
        ),
    ]
