# Generated by Django 5.1.1 on 2025-01-05 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0013_alter_addleisurepage_facultyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addleisurepage',
            name='facultyname',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='duty.addfaculty'),
            preserve_default=False,
        ),
    ]
