# Generated by Django 5.1.1 on 2025-01-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0014_alter_addleisurepage_facultyname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addleisurepage',
            old_name='facultyname',
            new_name='available',
        ),
    ]
