# Generated by Django 5.1.1 on 2025-01-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0018_alter_schedule_facultyname1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='facultyname1',
            field=models.CharField(max_length=100),
        ),
    ]
