# Generated by Django 5.1.1 on 2025-01-07 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0019_alter_schedule_facultyname1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='facultyname1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.addfaculty'),
        ),
    ]
