# Generated by Django 5.1.1 on 2025-01-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0020_alter_schedule_facultyname1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfaculty',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='addfaculty',
            name='qualification',
            field=models.CharField(choices=[('M', 'M.TECH'), ('M', 'MBA'), ('M', 'MCA'), ('M', 'MSC'), ('D', 'DEGREE'), ('B', 'BTECH')], max_length=100),
        ),
    ]
