# Generated by Django 5.1.1 on 2025-01-08 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0021_alter_addfaculty_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='facultyname1',
        ),
    ]
