# Generated by Django 5.1.1 on 2025-01-09 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0028_remove_schedule_facultyname1'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='facultyname1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='duty.addfaculty'),
            preserve_default=False,
        ),
    ]
