# Generated by Django 5.1.1 on 2025-01-09 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0029_schedule_facultyname1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='facultyname1',
        ),
    ]
